info:
  contact: {}
paths:
  /api/v1/ports:
    get:
      consumes:
      - application/json
      parameters:
      - description: page query
        in: query
        name: page
        type: string
      - description: page limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - port
  /api/v1/ports/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: port id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - port
swagger: "2.0"
